//! @generated by UnityShaderConverter — do not edit.
//! Unity shader: `FurFX/1.0/FurFX Advanced Shell 10 Layer`
//! Source: `third_party/Resonite.UnityShaders/Assets/Shaders/FurFX/Shaders/FurFX Advanced Shell 10Layer.shader`
//! One WGSL file per pass (named from ShaderLab `Name` or `passN`).
//! WGSL `override` / `@id` constants use `wgpu::PipelineCompilationOptions` on vertex and fragment stages (wgpu 28).
//! Texture properties on `Material` use `TextureHandle` (default `0`); host defines invalid/unbound semantics.

use glam::Vec4;
use crate::scene::types::TextureHandle;

/// No `multi_compile` specialization axes were extracted; pipeline constants are unused.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct VariantKey;

/// Merged vertex + fragment WGSL for pass 0.
pub const PASS0_WGSL: &str = include_str!("pass0.wgsl");

/// Merged vertex + fragment WGSL for pass 1.
pub const PASS1_WGSL: &str = include_str!("pass1.wgsl");

/// Merged vertex + fragment WGSL for pass 2.
pub const PASS2_WGSL: &str = include_str!("pass2.wgsl");

/// Merged vertex + fragment WGSL for pass 3.
pub const PASS3_WGSL: &str = include_str!("pass3.wgsl");

/// Merged vertex + fragment WGSL for pass 4.
pub const PASS4_WGSL: &str = include_str!("pass4.wgsl");

/// Merged vertex + fragment WGSL for pass 5.
pub const PASS5_WGSL: &str = include_str!("pass5.wgsl");

/// Merged vertex + fragment WGSL for pass 6.
pub const PASS6_WGSL: &str = include_str!("pass6.wgsl");

/// Merged vertex + fragment WGSL for pass 7.
pub const PASS7_WGSL: &str = include_str!("pass7.wgsl");

/// Merged vertex + fragment WGSL for pass 8.
pub const PASS8_WGSL: &str = include_str!("pass8.wgsl");

/// Merged vertex + fragment WGSL for pass 9.
pub const PASS9_WGSL: &str = include_str!("pass9.wgsl");

/// Default material values mapped from the Unity Properties block.
#[derive(Clone, Debug, PartialEq)]
pub struct Material {
    pub color: Vec4, // Color (RGB)
    pub specColor: Vec4, // Specular Material Color (RGB)
    pub rimColor: Vec4, // Rim Color
    pub rimPower: f32, // Rim Power
    pub shininess: f32, // Shininess
    pub furLength: f32, // Fur Length
    pub mainTex: TextureHandle, // Base (RGB) Mask(A)
    pub noiseTex: TextureHandle, // Noise (RGB)
    pub cube: TextureHandle, // Reflection Map
    pub reflection: f32, // Reflection Power
    pub cutoff: f32, // Alpha Cutoff
    pub edgeFade: f32, // Edge Fade
    pub hairHardness: f32, // Fur Hardness
    pub hairThinness: f32, // Fur Thinness
    pub hairShading: f32, // Fur Shading
    pub hairColoring: f32, // Fur Coloring
    pub skinAlpha: f32, // Mask Alpha Factor
    pub forceGlobal: Vec4, // Force Global
    pub forceLocal: Vec4, // Force Local
}

impl Default for Material {
    fn default() -> Self {
        Self {
            color: Vec4::new(1.0, 1.0, 1.0, 1.0),
            specColor: Vec4::new(1.0, 1.0, 1.0, 1.0),
            rimColor: Vec4::new(0.0, 0.0, 0.0, 0.0),
            rimPower: 4,
            shininess: 8,
            furLength: 0.05,
            mainTex: 0,
            noiseTex: 0,
            cube: 0,
            reflection: 0,
            cutoff: 0.0001,
            edgeFade: 0.15,
            hairHardness: 1,
            hairThinness: 2,
            hairShading: 0.25,
            hairColoring: 0.1,
            skinAlpha: 0.5,
            forceGlobal: Vec4::new(0.0, 0.0, 0.0, 0.0),
            forceLocal: Vec4::new(0.0, 0.0, 0.0, 0.0),
        }
    }
}

/// WGSL source for use with `Device::create_shader_module`.
pub fn shader_source_pass0() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS0_WGSL.into())
}

pub fn shader_source_pass1() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS1_WGSL.into())
}

pub fn shader_source_pass2() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS2_WGSL.into())
}

pub fn shader_source_pass3() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS3_WGSL.into())
}

pub fn shader_source_pass4() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS4_WGSL.into())
}

pub fn shader_source_pass5() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS5_WGSL.into())
}

pub fn shader_source_pass6() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS6_WGSL.into())
}

pub fn shader_source_pass7() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS7_WGSL.into())
}

pub fn shader_source_pass8() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS8_WGSL.into())
}

pub fn shader_source_pass9() -> wgpu::ShaderSource<'static> {
    wgpu::ShaderSource::Wgsl(PASS9_WGSL.into())
}

/// No interleaved vertex attributes were extracted for pass 0; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS0: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 1; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS1: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 2; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS2: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 3; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS3: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 4; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS4: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 5; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS5: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 6; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS6: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 7; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS7: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 8; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS8: &[wgpu::VertexBufferLayout] = &[];

/// No interleaved vertex attributes were extracted for pass 9; supply `vertex_layout_override` or fix WGSL.
pub static VERTEX_BUFFER_LAYOUTS_PASS9: &[wgpu::VertexBufferLayout] = &[];

/// Uniform buffer layout matching the prepended WGSL `MaterialUniform` (std140 with explicit padding).
#[repr(C, align(16))]
#[allow(dead_code)]
pub struct MaterialUniform {
    pub color: Vec4,
    pub specColor: Vec4,
    pub rimColor: Vec4,
    pub rimPower: f32,
    pub shininess: f32,
    pub furLength: f32,
    pub reflection: f32,
    pub cutoff: f32,
    pub edgeFade: f32,
    pub hairHardness: f32,
    pub hairThinness: f32,
    pub hairShading: f32,
    pub hairColoring: f32,
    pub skinAlpha: f32,
    pub _pad0: u32,
    pub forceGlobal: Vec4,
    pub forceLocal: Vec4,
}

fn pipeline_compilation_options_vertex_inner(_variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    wgpu::PipelineCompilationOptions::default()
}

/// Builds `PipelineCompilationOptions` for vertex/fragment stages (WGSL `override` / `@id`).
/// Note: leaks a tiny slice per call; cache by `VariantKey` in hot paths.
/// Per-pass wrappers delegate to the same implementation (specialization is per-shader).
pub fn pipeline_compilation_options_pass0_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass0_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass1_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass1_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass2_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass2_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass3_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass3_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass4_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass4_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass5_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass5_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass6_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass6_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass7_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass7_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass8_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass8_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass9_vertex(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

pub fn pipeline_compilation_options_pass9_fragment(variant: &VariantKey) -> wgpu::PipelineCompilationOptions<'static> {
    pipeline_compilation_options_vertex_inner(variant)
}

/// Bind group 1: `MaterialUniform` at binding 0, then each texture + sampler pair.
fn push_material_bind_group_layout_entries(entries: &mut Vec<wgpu::BindGroupLayoutEntry>) {
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 0,
        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Uniform,
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    });
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 1,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Texture {
            sample_type: wgpu::TextureSampleType::Float { filterable: true },
            view_dimension: wgpu::TextureViewDimension::D2,
            multisampled: false,
        },
        count: None,
    });
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 2,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
        count: None,
    });
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 3,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Texture {
            sample_type: wgpu::TextureSampleType::Float { filterable: true },
            view_dimension: wgpu::TextureViewDimension::D2,
            multisampled: false,
        },
        count: None,
    });
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 4,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
        count: None,
    });
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 5,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Texture {
            sample_type: wgpu::TextureSampleType::Float { filterable: true },
            view_dimension: wgpu::TextureViewDimension::Cube,
            multisampled: false,
        },
        count: None,
    });
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 6,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
        count: None,
    });
}

pub fn create_material_bind_group_layout(device: &wgpu::Device, label: &str) -> wgpu::BindGroupLayout {
    let mut entries = Vec::new();
    push_material_bind_group_layout_entries(&mut entries);
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some(label),
        entries: &entries,
    })
}

/// `texture_views_and_samplers` must contain one `(view, sampler)` per texture property in Properties order.
pub fn create_material_bind_group(
    device: &wgpu::Device,
    layout: &wgpu::BindGroupLayout,
    label: &str,
    material_uniform_buffer: &wgpu::Buffer,
    texture_views_and_samplers: &[(&wgpu::TextureView, &wgpu::Sampler)],
) -> wgpu::BindGroup {
    let mut entries: Vec<wgpu::BindGroupEntry> = Vec::new();
    entries.push(wgpu::BindGroupEntry {
        binding: 0,
        resource: wgpu::BindingResource::Buffer(wgpu::BufferBinding {
            buffer: material_uniform_buffer,
            offset: 0,
            size: None,
        }),
    });
    let mut b: u32 = 1;
    for (view, sampler) in texture_views_and_samplers {
        entries.push(wgpu::BindGroupEntry {
            binding: b,
            resource: wgpu::BindingResource::TextureView(view),
        });
        b += 1;
        entries.push(wgpu::BindGroupEntry {
            binding: b,
            resource: wgpu::BindingResource::Sampler(sampler),
        });
        b += 1;
    }
    device.create_bind_group(&wgpu::BindGroupDescriptor { label: Some(label), layout, entries: &entries })
}

/// Primitive assembly for pass 0 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass0() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 0 when a depth attachment is used.
pub fn depth_stencil_state_pass0(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 0 (blend + write mask from ShaderLab).
pub fn color_target_state_pass0(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 1 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass1() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 1 when a depth attachment is used.
pub fn depth_stencil_state_pass1(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 1 (blend + write mask from ShaderLab).
pub fn color_target_state_pass1(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 2 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass2() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 2 when a depth attachment is used.
pub fn depth_stencil_state_pass2(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 2 (blend + write mask from ShaderLab).
pub fn color_target_state_pass2(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 3 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass3() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 3 when a depth attachment is used.
pub fn depth_stencil_state_pass3(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 3 (blend + write mask from ShaderLab).
pub fn color_target_state_pass3(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 4 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass4() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 4 when a depth attachment is used.
pub fn depth_stencil_state_pass4(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 4 (blend + write mask from ShaderLab).
pub fn color_target_state_pass4(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 5 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass5() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 5 when a depth attachment is used.
pub fn depth_stencil_state_pass5(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 5 (blend + write mask from ShaderLab).
pub fn color_target_state_pass5(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 6 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass6() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 6 when a depth attachment is used.
pub fn depth_stencil_state_pass6(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 6 (blend + write mask from ShaderLab).
pub fn color_target_state_pass6(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 7 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass7() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 7 when a depth attachment is used.
pub fn depth_stencil_state_pass7(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 7 (blend + write mask from ShaderLab).
pub fn color_target_state_pass7(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 8 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass8() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 8 when a depth attachment is used.
pub fn depth_stencil_state_pass8(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 8 (blend + write mask from ShaderLab).
pub fn color_target_state_pass8(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Primitive assembly for pass 9 (from ShaderLab `Cull`). Tags: ` IgnoreProjector` = `True`; `LightMode` = `ForwardBase`; `QUEUE` = `Transparent`; `RenderType` = `Opaque`.
pub fn primitive_state_pass9() -> wgpu::PrimitiveState {
    wgpu::PrimitiveState {
        topology: wgpu::PrimitiveTopology::TriangleList,
        strip_index_format: None,
        front_face: wgpu::FrontFace::Ccw,
        cull_mode: Some(wgpu::Face::Back),
        unclipped_depth: false,
        polygon_mode: wgpu::PolygonMode::Fill,
        conservative: false,
    }
}

/// Depth/stencil for pass 9 when a depth attachment is used.
pub fn depth_stencil_state_pass9(depth_format: wgpu::TextureFormat) -> wgpu::DepthStencilState {
    wgpu::DepthStencilState {
        format: depth_format,
        depth_write_enabled: true,
        depth_compare: wgpu::CompareFunction::LessEqual,
        stencil: wgpu::StencilState {
        front: wgpu::StencilFaceState::IGNORE,
        back: wgpu::StencilFaceState::IGNORE,
        read_mask: 0,
        write_mask: 0,
    },
        bias: wgpu::DepthBiasState {
            constant: 0,
            slope_scale: 0.0,
            clamp: 0.0,
        },
    }
}

/// First color target for pass 9 (blend + write mask from ShaderLab).
pub fn color_target_state_pass9(surface_format: wgpu::TextureFormat) -> Option<wgpu::ColorTargetState> {
    Some(wgpu::ColorTargetState {
                format: surface_format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
}

/// Builds a render pipeline for pass 0 using generated fixed-function state.
pub fn create_render_pipeline_pass0(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS0 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass0(),
    });
    let vertex_opts = pipeline_compilation_options_pass0_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass0_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass0(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass0(),
        depth_stencil: depth_format.map(depth_stencil_state_pass0),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 1 using generated fixed-function state.
pub fn create_render_pipeline_pass1(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS1 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass1(),
    });
    let vertex_opts = pipeline_compilation_options_pass1_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass1_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass1(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass1(),
        depth_stencil: depth_format.map(depth_stencil_state_pass1),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 2 using generated fixed-function state.
pub fn create_render_pipeline_pass2(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS2 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass2(),
    });
    let vertex_opts = pipeline_compilation_options_pass2_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass2_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass2(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass2(),
        depth_stencil: depth_format.map(depth_stencil_state_pass2),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 3 using generated fixed-function state.
pub fn create_render_pipeline_pass3(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS3 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass3(),
    });
    let vertex_opts = pipeline_compilation_options_pass3_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass3_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass3(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass3(),
        depth_stencil: depth_format.map(depth_stencil_state_pass3),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 4 using generated fixed-function state.
pub fn create_render_pipeline_pass4(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS4 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass4(),
    });
    let vertex_opts = pipeline_compilation_options_pass4_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass4_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass4(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass4(),
        depth_stencil: depth_format.map(depth_stencil_state_pass4),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 5 using generated fixed-function state.
pub fn create_render_pipeline_pass5(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS5 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass5(),
    });
    let vertex_opts = pipeline_compilation_options_pass5_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass5_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass5(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass5(),
        depth_stencil: depth_format.map(depth_stencil_state_pass5),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 6 using generated fixed-function state.
pub fn create_render_pipeline_pass6(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS6 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass6(),
    });
    let vertex_opts = pipeline_compilation_options_pass6_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass6_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass6(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass6(),
        depth_stencil: depth_format.map(depth_stencil_state_pass6),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 7 using generated fixed-function state.
pub fn create_render_pipeline_pass7(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS7 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass7(),
    });
    let vertex_opts = pipeline_compilation_options_pass7_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass7_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass7(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass7(),
        depth_stencil: depth_format.map(depth_stencil_state_pass7),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 8 using generated fixed-function state.
pub fn create_render_pipeline_pass8(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS8 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass8(),
    });
    let vertex_opts = pipeline_compilation_options_pass8_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass8_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass8(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass8(),
        depth_stencil: depth_format.map(depth_stencil_state_pass8),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Builds a render pipeline for pass 9 using generated fixed-function state.
pub fn create_render_pipeline_pass9(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    let vertex_buffers: &[wgpu::VertexBufferLayout] = match vertex_layout_override { Some(b) => b, None => VERTEX_BUFFER_LAYOUTS_PASS9 };
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("FurFX/1.0/FurFX Advanced Shell 10 Layer"),
        source: shader_source_pass9(),
    });
    let vertex_opts = pipeline_compilation_options_pass9_vertex(variant);
    let fragment_opts = pipeline_compilation_options_pass9_fragment(variant);
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("VertexProgram"),
            buffers: vertex_buffers,
            compilation_options: vertex_opts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("frag"),
            targets: &[color_target_state_pass9(surface_format)],
            compilation_options: fragment_opts,
        }),
        primitive: primitive_state_pass9(),
        depth_stencil: depth_format.map(depth_stencil_state_pass9),
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

/// Dispatches to `create_render_pipeline_passN` by index. Panics if `pass_index` is out of range.
#[allow(clippy::too_many_arguments)]
pub fn create_render_pipeline(
    device: &wgpu::Device,
    label: &str,
    layout: &wgpu::PipelineLayout,
    surface_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    variant: &VariantKey,
    pass_index: usize,
    vertex_layout_override: Option<&[wgpu::VertexBufferLayout]>,
) -> wgpu::RenderPipeline {
    match pass_index {
        0 => create_render_pipeline_pass0(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        1 => create_render_pipeline_pass1(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        2 => create_render_pipeline_pass2(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        3 => create_render_pipeline_pass3(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        4 => create_render_pipeline_pass4(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        5 => create_render_pipeline_pass5(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        6 => create_render_pipeline_pass6(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        7 => create_render_pipeline_pass7(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        8 => create_render_pipeline_pass8(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        9 => create_render_pipeline_pass9(device, label, layout, surface_format, depth_format, variant, vertex_layout_override),
        _ => panic!("invalid pass_index for this shader module"),
    }
}
/// Vertex shader entry name produced by Slang for pass 0.
pub const VERTEX_ENTRY_PASS0: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS0: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 1.
pub const VERTEX_ENTRY_PASS1: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS1: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 2.
pub const VERTEX_ENTRY_PASS2: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS2: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 3.
pub const VERTEX_ENTRY_PASS3: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS3: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 4.
pub const VERTEX_ENTRY_PASS4: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS4: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 5.
pub const VERTEX_ENTRY_PASS5: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS5: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 6.
pub const VERTEX_ENTRY_PASS6: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS6: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 7.
pub const VERTEX_ENTRY_PASS7: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS7: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 8.
pub const VERTEX_ENTRY_PASS8: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS8: &str = "frag";

/// Vertex shader entry name produced by Slang for pass 9.
pub const VERTEX_ENTRY_PASS9: &str = "VertexProgram";
pub const FRAGMENT_ENTRY_PASS9: &str = "frag";

/// Pass names from ShaderLab (for future pipeline / file naming).
pub const PASS_0_NAME: &str = "pass_0";
pub const PASS_1_NAME: &str = "pass_1";
pub const PASS_2_NAME: &str = "pass_2";
pub const PASS_3_NAME: &str = "pass_3";
pub const PASS_4_NAME: &str = "pass_4";
pub const PASS_5_NAME: &str = "pass_5";
pub const PASS_6_NAME: &str = "pass_6";
pub const PASS_7_NAME: &str = "pass_7";
pub const PASS_8_NAME: &str = "pass_8";
pub const PASS_9_NAME: &str = "pass_9";
