//! Dirty expansion and retained render-world maintenance passes.

use hashbrown::{HashMap, HashSet};
use rayon::prelude::*;

use crate::gpu_pools::MeshPool;
use crate::scene::{
    RenderSpaceId, RenderSpaceRead, RenderWorldBoundsDirty, RenderWorldRendererDirty,
    RenderWorldRendererKind, RenderWorldTransformDirty, WorldMeshSceneRead,
};
use crate::shared::RenderingContext;

use super::refresh::{
    DirtyRendererSet, RefreshOutcome, refresh_render_world_space, refresh_renderer_bounds_set,
    refresh_renderer_set,
};
use super::state::{RenderWorldRendererRef, RenderWorldSpace};
use super::{
    RenderWorld, RenderWorldDirtyReason, RenderWorldMaintenanceStats, dirty_refresh_admission,
    mesh_asset_expansion_admission, node_is_under_any_root, transform_root_expansion_admission,
    transform_root_node_scan_admission, transform_roots_cover_space,
};
use crate::cpu_parallelism::{FrameParallelPolicy, current_reference_worker_count};

/// Minimum retained node-index entries assigned to one transform expansion worker.
///
/// Transform classification is branchy and performs very little work per indexed node once
/// ancestor results are memoized. Grains this coarse keep ordinary character spaces down to a
/// handful of Rayon jobs; finer ones burn more aggregate worker time than they save in wall time.
const TRANSFORM_NODE_SCAN_MIN_ENTRIES_PER_TASK: usize = 8_192;
/// Maximum coarse packets generated by either transform expansion fan-out.
const TRANSFORM_EXPANSION_MAX_TASKS: usize = 8;

const TRANSFORM_NODE_UNKNOWN: u8 = 0;
const TRANSFORM_NODE_OUTSIDE_ROOTS: u8 = 1;
const TRANSFORM_NODE_UNDER_ROOT: u8 = 2;
const TRANSFORM_NODE_VISITING: u8 = 3;

/// Counters gathered while expanding deferred transform-root dirties.
#[derive(Default)]
pub(super) struct TransformDirtyExpansionStats {
    /// Unique transform-root node ids consumed.
    root_count: usize,
    /// Retained node-index entries scanned.
    scanned_node_count: usize,
    /// Renderer records found by retained reverse-index expansion.
    expanded_renderer_count: usize,
    /// Transform roots that covered all cached renderer records in a space.
    full_space_root_count: usize,
    /// Unique hierarchy nodes resolved while classifying retained node-index entries.
    classified_hierarchy_node_count: usize,
}

/// Result of expanding one transform-root dirty input.
enum TransformDirtyExpansion {
    /// The render space was removed from the scene.
    Removed(RenderSpaceId),
    /// The render space has no retained cache and needs a full rebuild.
    FullSpace(RenderSpaceId),
    /// The dirty roots expanded to renderer records.
    Renderers(Vec<RenderWorldRendererDirty>),
    /// No retained renderer records were affected.
    Empty,
}

/// Result of expanding one transform-root dirty input with accounting.
struct TransformDirtyExpansionResult {
    /// Dirty-expansion action to apply to render-world dirty sets.
    expansion: TransformDirtyExpansion,
    /// Number of unique transform-root node ids represented by this coalesced result.
    root_count: usize,
    /// Retained node-index entries scanned while expanding this dirty record.
    scanned_node_count: usize,
    /// Whether the dirty roots covered the entire retained render space.
    full_space_root: bool,
    /// Unique hierarchy nodes resolved while classifying retained node-index entries.
    classified_hierarchy_node_count: usize,
}

/// Renderer dirties and work accounting produced by one retained node-index scan.
struct TransformNodeIndexExpansion {
    renderers: Vec<RenderWorldRendererDirty>,
    scanned_node_count: usize,
    classified_hierarchy_node_count: usize,
}

/// Memoized descendant classifier for one coalesced transform-root set.
///
/// Each hierarchy node transitions out of `UNKNOWN` at most once. This changes classification from
/// `indexed nodes * roots * ancestor depth` parent-table reads to `indexed nodes + unique visited
/// ancestors`, while preserving malformed-parent and cycle behavior.
struct TransformRootClassifier<'a> {
    parents: &'a [i32],
    roots: &'a [i32],
    states: Vec<u8>,
    path: Vec<usize>,
    classified_hierarchy_node_count: usize,
}

impl<'a> TransformRootClassifier<'a> {
    fn new(parents: &'a [i32], roots: &'a [i32]) -> Self {
        let mut states = vec![TRANSFORM_NODE_UNKNOWN; parents.len()];
        for &root in roots {
            if root >= 0 {
                if let Some(state) = states.get_mut(root as usize) {
                    *state = TRANSFORM_NODE_UNDER_ROOT;
                }
            }
        }
        Self {
            parents,
            roots,
            states,
            path: Vec::new(),
            classified_hierarchy_node_count: 0,
        }
    }

    /// Returns whether `node_id` is equal to or below any dirty root.
    fn is_under_root(&mut self, node_id: i32) -> bool {
        if node_id < 0 {
            return false;
        }
        if node_id as usize >= self.parents.len() {
            // Preserve the legacy malformed-id behavior: an out-of-range renderer node still
            // matches an identical dirty root before parent lookup fails.
            return node_is_under_any_root(self.parents, node_id, self.roots);
        }

        self.path.clear();
        let mut current = node_id;
        let under_root = loop {
            if current < 0 {
                break false;
            }
            let current_index = current as usize;
            let Some(&state) = self.states.get(current_index) else {
                // The legacy walk can match an out-of-range parent when that exact id is a root.
                break self.roots.contains(&current);
            };
            match state {
                TRANSFORM_NODE_OUTSIDE_ROOTS => break false,
                TRANSFORM_NODE_UNDER_ROOT => break true,
                TRANSFORM_NODE_VISITING => {
                    // A cycle that did not encounter a root is outside the requested subtrees.
                    break false;
                }
                TRANSFORM_NODE_UNKNOWN => {
                    self.states[current_index] = TRANSFORM_NODE_VISITING;
                    self.path.push(current_index);
                    current = self.parents[current_index];
                }
                _ => unreachable!("transform-node classification state must be valid"),
            }
        };

        let resolved_state = if under_root {
            TRANSFORM_NODE_UNDER_ROOT
        } else {
            TRANSFORM_NODE_OUTSIDE_ROOTS
        };
        self.classified_hierarchy_node_count += self.path.len();
        for &node_index in &self.path {
            self.states[node_index] = resolved_state;
        }
        under_root
    }
}

/// Worker-owned full-space refresh payload.
struct DirtySpaceRefreshWork {
    /// Render space being refreshed.
    id: RenderSpaceId,
    /// Estimated renderer/template work used for parallel admission.
    estimated_work_units: usize,
    /// Retained cache removed from [`RenderWorld::spaces`] for worker-owned mutation.
    cached: RenderWorldSpace,
    /// Refresh counters produced by the worker.
    outcome: RefreshOutcome,
}

/// Worker-owned partial-renderer refresh payload.
struct DirtyRendererRefreshWork {
    /// Render space containing the dirty renderer records.
    id: RenderSpaceId,
    /// Dirty renderer records grouped for this space.
    dirty_set: DirtyRendererSet,
    /// Estimated renderer/template work used for parallel admission.
    estimated_work_units: usize,
    /// Retained cache removed from [`RenderWorld::spaces`] for worker-owned mutation.
    cached: RenderWorldSpace,
    /// Refresh counters produced by the worker.
    outcome: RefreshOutcome,
}

/// Worker-owned dynamic-bounds refresh payload.
struct DirtyBoundsRefreshWork {
    /// Render space containing the dirty renderer records.
    id: RenderSpaceId,
    /// Dirty bounds records grouped for this space.
    dirty_set: DirtyRendererSet,
    /// Estimated renderer work used for parallel admission.
    estimated_work_units: usize,
    /// Retained cache removed from [`RenderWorld::spaces`] for worker-owned mutation.
    cached: RenderWorldSpace,
    /// Refresh counters produced by the worker.
    outcome: RefreshOutcome,
}

/// Coalesces transform-root dirty inputs by render space while preserving first-seen space order.
fn coalesce_transform_dirty_roots(
    roots: Vec<RenderWorldTransformDirty>,
) -> Vec<RenderWorldTransformDirty> {
    let mut order = Vec::new();
    let mut by_space: HashMap<RenderSpaceId, (Vec<i32>, HashSet<i32>)> = HashMap::new();
    for dirty in roots {
        if !by_space.contains_key(&dirty.space_id) {
            order.push(dirty.space_id);
        }
        let (root_node_ids, seen_roots) = by_space.entry(dirty.space_id).or_default();
        for root_node_id in dirty.root_node_ids {
            if seen_roots.insert(root_node_id) {
                root_node_ids.push(root_node_id);
            }
        }
    }
    order
        .into_iter()
        .filter_map(|space_id| {
            by_space
                .remove(&space_id)
                .map(|(root_node_ids, _)| RenderWorldTransformDirty {
                    space_id,
                    root_node_ids,
                })
        })
        .collect()
}

/// Returns a coarse packet size bounded by the useful worker count.
fn coarsened_transform_chunk_size(
    item_count: usize,
    admitted_chunk_size: usize,
    minimum_chunk_size: usize,
    worker_count: usize,
) -> usize {
    let target_tasks = worker_count.clamp(1, TRANSFORM_EXPANSION_MAX_TASKS);
    admitted_chunk_size
        .max(minimum_chunk_size)
        .max(item_count.div_ceil(target_tasks))
}

/// Appends renderer dirty records referenced by one matching retained node-index entry.
fn push_transform_node_renderer_dirties(
    renderers: &mut Vec<RenderWorldRendererDirty>,
    space_id: RenderSpaceId,
    refs: &[RenderWorldRendererRef],
) {
    renderers.extend(refs.iter().map(|renderer| RenderWorldRendererDirty {
        space_id,
        kind: renderer.kind,
        renderable_index: renderer.index,
    }));
}

/// Classifies and expands a sequence of retained node-index entries.
fn expand_transform_node_entries<'a>(
    space_id: RenderSpaceId,
    entries: impl IntoIterator<Item = (i32, &'a [RenderWorldRendererRef])>,
    parents: &'a [i32],
    roots: &'a [i32],
) -> TransformNodeIndexExpansion {
    let mut classifier = TransformRootClassifier::new(parents, roots);
    let mut renderers = Vec::new();
    let mut scanned_node_count = 0;
    for (node_id, refs) in entries {
        scanned_node_count += 1;
        if classifier.is_under_root(node_id) {
            push_transform_node_renderer_dirties(&mut renderers, space_id, refs);
        }
    }
    TransformNodeIndexExpansion {
        renderers,
        scanned_node_count,
        classified_hierarchy_node_count: classifier.classified_hierarchy_node_count,
    }
}

/// Returns retained renderer dirty records for every valid cached renderer in a space.
fn cached_renderer_dirties_for_space(
    space_id: RenderSpaceId,
    cached: &RenderWorldSpace,
) -> Vec<RenderWorldRendererDirty> {
    cached
        .static_renderers
        .iter()
        .enumerate()
        .filter(|(_, renderer)| renderer.node_id >= 0)
        .map(|(renderable_index, _)| RenderWorldRendererDirty {
            space_id,
            kind: RenderWorldRendererKind::Static,
            renderable_index,
        })
        .chain(
            cached
                .skinned_renderers
                .iter()
                .enumerate()
                .filter(|(_, renderer)| renderer.node_id >= 0)
                .map(|(renderable_index, _)| RenderWorldRendererDirty {
                    space_id,
                    kind: RenderWorldRendererKind::Skinned,
                    renderable_index,
                }),
        )
        .collect()
}

impl RenderWorld {
    /// Expands deferred transform-root and mesh-asset dirties into renderer-record dirties.
    pub(super) fn expand_deferred_dirty_inputs<S>(
        &mut self,
        scene: &S,
        stats: &mut RenderWorldMaintenanceStats,
    ) where
        S: WorldMeshSceneRead + Sync + ?Sized,
    {
        let transform_stats = self.expand_dirty_transform_roots(scene);
        stats.transform_root_dirty_count += transform_stats.root_count;
        stats.transform_root_scanned_node_count += transform_stats.scanned_node_count;
        stats.transform_root_expanded_renderer_count += transform_stats.expanded_renderer_count;
        stats.transform_root_full_space_count += transform_stats.full_space_root_count;
        self.expand_dirty_mesh_assets();
    }

    /// Expands transform-root dirties to descendant renderer records.
    pub(super) fn expand_dirty_transform_roots<S>(
        &mut self,
        scene: &S,
    ) -> TransformDirtyExpansionStats
    where
        S: WorldMeshSceneRead + Sync + ?Sized,
    {
        if self.dirty_transform_roots.is_empty() {
            return TransformDirtyExpansionStats::default();
        }
        profiling::scope!("mesh::render_world::expand_transform_roots");
        let roots = coalesce_transform_dirty_roots(std::mem::take(&mut self.dirty_transform_roots));
        let policy = FrameParallelPolicy::for_current_thread_pool();
        let expansion_admission = transform_root_expansion_admission(policy, roots.len());
        let expansions = match expansion_admission.chunk_size() {
            Some(admitted_chunk_size) => {
                let chunk_size = coarsened_transform_chunk_size(
                    roots.len(),
                    admitted_chunk_size,
                    admitted_chunk_size,
                    current_reference_worker_count(),
                );
                roots
                    .par_chunks(chunk_size)
                    .map(|chunk| {
                        profiling::scope!(
                            "mesh::render_world::expand_transform_roots::space_worker"
                        );
                        chunk
                            .iter()
                            .map(|dirty| self.expand_transform_dirty(scene, dirty, false))
                            .collect::<Vec<_>>()
                    })
                    .reduce(Vec::new, |mut left, mut right| {
                        left.append(&mut right);
                        left
                    })
            }
            None => roots
                .iter()
                .map(|dirty| self.expand_transform_dirty(scene, dirty, true))
                .collect(),
        };
        let stats = self.apply_transform_dirty_expansions(expansions);
        #[cfg(feature = "tracy")]
        tracy_client::plot!(
            "render_world::transform_root_classified_hierarchy_nodes",
            stats.classified_hierarchy_node_count as f64
        );
        stats
    }

    /// Expands one transform-root dirty input using retained node reverse indexes.
    fn expand_transform_dirty<S>(
        &self,
        scene: &S,
        dirty: &RenderWorldTransformDirty,
        allow_node_scan_parallel: bool,
    ) -> TransformDirtyExpansionResult
    where
        S: WorldMeshSceneRead + ?Sized,
    {
        let root_count = dirty.root_node_ids.len();
        if self.dirty_spaces.contains(&dirty.space_id) {
            return TransformDirtyExpansionResult {
                expansion: TransformDirtyExpansion::Empty,
                root_count,
                scanned_node_count: 0,
                full_space_root: false,
                classified_hierarchy_node_count: 0,
            };
        }
        let Some(space_view) = scene.space(dirty.space_id) else {
            return TransformDirtyExpansionResult {
                expansion: TransformDirtyExpansion::Removed(dirty.space_id),
                root_count,
                scanned_node_count: 0,
                full_space_root: false,
                classified_hierarchy_node_count: 0,
            };
        };
        let Some(cached) = self.spaces.get(&dirty.space_id) else {
            return TransformDirtyExpansionResult {
                expansion: TransformDirtyExpansion::FullSpace(dirty.space_id),
                root_count,
                scanned_node_count: 0,
                full_space_root: false,
                classified_hierarchy_node_count: 0,
            };
        };
        let parents = space_view.node_parents();
        let full_space_root = transform_roots_cover_space(parents, &dirty.root_node_ids);
        let node_expansion = if full_space_root {
            TransformNodeIndexExpansion {
                renderers: cached_renderer_dirties_for_space(dirty.space_id, cached),
                scanned_node_count: 0,
                classified_hierarchy_node_count: 0,
            }
        } else {
            self.expand_transform_dirty_by_node_index(
                cached,
                dirty,
                parents,
                allow_node_scan_parallel,
            )
        };
        let expansion = if node_expansion.renderers.is_empty() {
            TransformDirtyExpansion::Empty
        } else {
            TransformDirtyExpansion::Renderers(node_expansion.renderers)
        };
        TransformDirtyExpansionResult {
            expansion,
            root_count,
            scanned_node_count: node_expansion.scanned_node_count,
            full_space_root,
            classified_hierarchy_node_count: node_expansion.classified_hierarchy_node_count,
        }
    }

    /// Expands one transform dirty by scanning retained node reverse-index entries.
    fn expand_transform_dirty_by_node_index(
        &self,
        cached: &RenderWorldSpace,
        dirty: &RenderWorldTransformDirty,
        parents: &[i32],
        allow_parallel: bool,
    ) -> TransformNodeIndexExpansion {
        let node_count = cached.node_index.len();
        let policy = FrameParallelPolicy::for_current_thread_pool();
        let admitted_chunk_size = allow_parallel
            .then(|| transform_root_node_scan_admission(policy, node_count).chunk_size())
            .flatten();
        let parallel_chunk_size = admitted_chunk_size.and_then(|admitted_chunk_size| {
            let chunk_size = coarsened_transform_chunk_size(
                node_count,
                admitted_chunk_size,
                TRANSFORM_NODE_SCAN_MIN_ENTRIES_PER_TASK,
                current_reference_worker_count(),
            );
            (node_count.div_ceil(chunk_size) >= 2).then_some(chunk_size)
        });
        match parallel_chunk_size {
            Some(chunk_size) => {
                profiling::scope!("mesh::render_world::expand_transform_roots::node_scan_parallel");
                let entries = cached
                    .node_index
                    .iter()
                    .map(|(&node_id, refs)| (node_id, refs.as_slice()))
                    .collect::<Vec<_>>();
                entries
                    .par_chunks(chunk_size)
                    .with_min_len(1)
                    .map(|chunk| {
                        profiling::scope!(
                            "mesh::render_world::expand_transform_roots::node_scan_worker"
                        );
                        expand_transform_node_entries(
                            dirty.space_id,
                            chunk.iter().copied(),
                            parents,
                            &dirty.root_node_ids,
                        )
                    })
                    .reduce(
                        || TransformNodeIndexExpansion {
                            renderers: Vec::new(),
                            scanned_node_count: 0,
                            classified_hierarchy_node_count: 0,
                        },
                        |mut left, mut right| {
                            left.renderers.append(&mut right.renderers);
                            left.scanned_node_count += right.scanned_node_count;
                            left.classified_hierarchy_node_count +=
                                right.classified_hierarchy_node_count;
                            left
                        },
                    )
            }
            None => expand_transform_node_entries(
                dirty.space_id,
                cached
                    .node_index
                    .iter()
                    .map(|(&node_id, refs)| (node_id, refs.as_slice())),
                parents,
                &dirty.root_node_ids,
            ),
        }
    }

    /// Applies transform dirty expansion results to the retained cache's dirty sets.
    fn apply_transform_dirty_expansions(
        &mut self,
        expansions: Vec<TransformDirtyExpansionResult>,
    ) -> TransformDirtyExpansionStats {
        let mut stats = TransformDirtyExpansionStats::default();
        for expansion in expansions {
            stats.root_count += expansion.root_count;
            stats.scanned_node_count += expansion.scanned_node_count;
            stats.full_space_root_count += usize::from(expansion.full_space_root);
            stats.classified_hierarchy_node_count += expansion.classified_hierarchy_node_count;
            match expansion.expansion {
                TransformDirtyExpansion::Removed(space_id) => self.remove_space(space_id),
                TransformDirtyExpansion::FullSpace(space_id) => {
                    stats.expanded_renderer_count +=
                        self.note_space_transform_bounds_dirty(space_id);
                }
                TransformDirtyExpansion::Renderers(renderers) => {
                    stats.expanded_renderer_count += renderers.len();
                    for dirty in renderers {
                        self.note_bounds_dirty(
                            RenderWorldBoundsDirty {
                                space_id: dirty.space_id,
                                kind: dirty.kind,
                                renderable_index: dirty.renderable_index,
                            },
                            RenderWorldDirtyReason::TransformOnly,
                        );
                    }
                }
                TransformDirtyExpansion::Empty => {}
            }
        }
        stats
    }

    /// Marks every retained renderer in a space bounds-dirty after a space-wide transform change.
    ///
    /// A transform root covering the whole space moves every renderer in it, but draw templates are
    /// transform independent: only world matrices and cull bounds change. Marking the space dirty
    /// refreshes every template and rebuilds the prepared snapshot, which measured as the dominant
    /// per-frame cost in a world whose root ticks. The bounds path patches the retained prepared
    /// rows in place instead and leaves the snapshot intact.
    ///
    /// Falls back to a full space rebuild when nothing is retained yet, since there are no rows to
    /// patch. Returns the number of renderers marked.
    pub(super) fn note_space_transform_bounds_dirty(&mut self, space_id: RenderSpaceId) -> usize {
        if self.dirty_spaces.contains(&space_id) {
            return 0;
        }
        let Some(space) = self.spaces.get(&space_id) else {
            self.note_space_dirty(space_id);
            return 0;
        };
        let dirties = space
            .static_renderers
            .iter()
            .enumerate()
            .map(|(index, _)| (RenderWorldRendererKind::Static, index))
            .chain(
                space
                    .skinned_renderers
                    .iter()
                    .enumerate()
                    .map(|(index, _)| (RenderWorldRendererKind::Skinned, index)),
            )
            .map(|(kind, renderable_index)| RenderWorldBoundsDirty {
                space_id,
                kind,
                renderable_index,
            })
            .collect::<Vec<_>>();
        let count = dirties.len();
        for dirty in dirties {
            self.note_bounds_dirty(dirty, RenderWorldDirtyReason::TransformOnly);
        }
        count
    }

    /// Expands dirty mesh asset ids to renderer records through retained reverse indexes.
    pub(super) fn expand_dirty_mesh_assets(&mut self) {
        if self.dirty_mesh_assets.is_empty() {
            return;
        }
        profiling::scope!("mesh::render_world::expand_mesh_asset_dirties");
        let dirty_mesh_assets = std::mem::take(&mut self.dirty_mesh_assets);
        let spaces = self.spaces.iter().collect::<Vec<_>>();
        let collect_for_space = |(space_id, space): &(&RenderSpaceId, &RenderWorldSpace)| {
            let mut renderer_dirties = Vec::new();
            if self.dirty_spaces.contains(*space_id) {
                return renderer_dirties;
            }
            for asset_id in &dirty_mesh_assets {
                if let Some(renderers) = space.mesh_asset_index.get(asset_id) {
                    renderer_dirties.extend(renderers.iter().map(|renderer| {
                        RenderWorldRendererDirty {
                            space_id: **space_id,
                            kind: renderer.kind,
                            renderable_index: renderer.index,
                        }
                    }));
                }
            }
            renderer_dirties
        };
        let policy = FrameParallelPolicy::for_current_thread_pool();
        let renderer_dirties =
            match mesh_asset_expansion_admission(policy, spaces.len()).chunk_size() {
                Some(chunk_size) => spaces
                    .par_iter()
                    .with_min_len(chunk_size)
                    .flat_map(collect_for_space)
                    .collect::<Vec<_>>(),
                None => spaces.iter().flat_map(collect_for_space).collect(),
            };
        for dirty in renderer_dirties {
            self.note_renderer_dirty(dirty, RenderWorldDirtyReason::MeshAsset);
        }
    }

    /// Refreshes all spaces marked for full retained-template rebuild.
    pub(super) fn refresh_dirty_spaces<S>(
        &mut self,
        scene: &S,
        mesh_pool: &MeshPool,
        render_context: RenderingContext,
    ) -> RefreshOutcome
    where
        S: WorldMeshSceneRead + Sync + ?Sized,
    {
        profiling::scope!("mesh::render_world::refresh_dirty_spaces");
        let dirty_spaces = std::mem::take(&mut self.dirty_spaces);
        let mut work = Vec::with_capacity(dirty_spaces.len());
        for id in dirty_spaces {
            self.dirty_renderers.retain(|dirty, _| dirty.space_id != id);
            self.dirty_bounds_renderers
                .retain(|dirty, _| dirty.space_id != id);
            let cached = self.spaces.remove(&id).unwrap_or_default();
            let estimated_work_units = estimate_full_space_refresh_work(&cached, scene, id);
            work.push(DirtySpaceRefreshWork {
                id,
                estimated_work_units,
                cached,
                outcome: RefreshOutcome::default(),
            });
        }
        let estimated_work_units = work.iter().map(|work| work.estimated_work_units).sum();
        let policy = FrameParallelPolicy::for_current_thread_pool();
        match dirty_refresh_admission(policy, work.len(), estimated_work_units).chunk_size() {
            Some(chunk_size) => {
                work.par_iter_mut()
                    .with_min_len(chunk_size)
                    .for_each(|work| {
                        profiling::scope!("mesh::render_world::refresh_dirty_spaces::worker");
                        work.outcome = refresh_render_world_space(
                            &mut work.cached,
                            scene,
                            mesh_pool,
                            render_context,
                            work.id,
                        );
                    });
            }
            None => {
                for work in &mut work {
                    work.outcome = refresh_render_world_space(
                        &mut work.cached,
                        scene,
                        mesh_pool,
                        render_context,
                        work.id,
                    );
                }
            }
        }
        let mut outcome = RefreshOutcome::default();
        for work in work {
            outcome.renderer_count += work.outcome.renderer_count;
            outcome.template_count += work.outcome.template_count;
            outcome.full_space_count += work.outcome.full_space_count;
            if scene.space(work.id).is_some() {
                self.spaces.insert(work.id, work.cached);
            }
        }
        outcome
    }

    /// Refreshes individual renderer records marked dirty by scene or mesh-pool events.
    pub(super) fn refresh_dirty_renderers<S>(
        &mut self,
        scene: &S,
        mesh_pool: &MeshPool,
        render_context: RenderingContext,
    ) -> RefreshOutcome
    where
        S: WorldMeshSceneRead + Sync + ?Sized,
    {
        profiling::scope!("mesh::render_world::refresh_dirty_renderers");
        let dirty_renderers = std::mem::take(&mut self.dirty_renderers);
        self.dirty_bounds_renderers.retain(|dirty, _| {
            !dirty_renderers.contains_key(&RenderWorldRendererDirty {
                space_id: dirty.space_id,
                kind: dirty.kind,
                renderable_index: dirty.renderable_index,
            })
        });
        let mut by_space: HashMap<RenderSpaceId, DirtyRendererSet> = HashMap::new();
        for dirty in dirty_renderers.into_keys() {
            by_space
                .entry(dirty.space_id)
                .or_default()
                .insert(dirty.kind, dirty.renderable_index);
        }

        let mut outcome = RefreshOutcome::default();
        let mut work = Vec::with_capacity(by_space.len());
        for (space_id, dirty_set) in by_space {
            if dirty_set.is_empty() {
                continue;
            }
            if scene.space(space_id).is_none() {
                self.remove_space(space_id);
                continue;
            }
            let estimated_work_units = dirty_set.len();
            work.push(DirtyRendererRefreshWork {
                id: space_id,
                dirty_set,
                estimated_work_units,
                cached: self.spaces.remove(&space_id).unwrap_or_default(),
                outcome: RefreshOutcome::default(),
            });
        }
        let estimated_work_units = work.iter().map(|work| work.estimated_work_units).sum();
        let policy = FrameParallelPolicy::for_current_thread_pool();
        match dirty_refresh_admission(policy, work.len(), estimated_work_units).chunk_size() {
            Some(chunk_size) => {
                work.par_iter_mut()
                    .with_min_len(chunk_size)
                    .for_each(|work| {
                        profiling::scope!("mesh::render_world::refresh_dirty_renderers::worker");
                        work.outcome =
                            refresh_dirty_renderer_work(work, scene, mesh_pool, render_context);
                    });
            }
            None => {
                for work in &mut work {
                    work.outcome =
                        refresh_dirty_renderer_work(work, scene, mesh_pool, render_context);
                }
            }
        }
        for work in work {
            outcome.renderer_count += work.outcome.renderer_count;
            outcome.template_count += work.outcome.template_count;
            if scene.space(work.id).is_some() {
                self.spaces.insert(work.id, work.cached);
            }
        }
        outcome
    }

    /// Refreshes dynamic bounds for renderer records marked by transform-only scene changes.
    pub(super) fn refresh_dirty_bounds<S>(
        &mut self,
        scene: &S,
        mesh_pool: &MeshPool,
        render_context: RenderingContext,
    ) -> RefreshOutcome
    where
        S: WorldMeshSceneRead + Sync + ?Sized,
    {
        profiling::scope!("mesh::render_world::refresh_dirty_bounds");
        self.begin_bounds_patch_log();
        let dirty_bounds = std::mem::take(&mut self.dirty_bounds_renderers);
        let mut by_space: HashMap<RenderSpaceId, DirtyRendererSet> = HashMap::new();
        for dirty in dirty_bounds.into_keys() {
            by_space
                .entry(dirty.space_id)
                .or_default()
                .insert(dirty.kind, dirty.renderable_index);
        }

        let mut work = Vec::with_capacity(by_space.len());
        for (space_id, dirty_set) in by_space {
            if dirty_set.is_empty() {
                continue;
            }
            if scene.space(space_id).is_none() {
                self.remove_space(space_id);
                continue;
            }
            let Some(cached) = self.spaces.remove(&space_id) else {
                self.note_space_dirty(space_id);
                continue;
            };
            let estimated_work_units = dirty_set.len();
            work.push(DirtyBoundsRefreshWork {
                id: space_id,
                dirty_set,
                estimated_work_units,
                cached,
                outcome: RefreshOutcome::default(),
            });
        }
        let estimated_work_units = work.iter().map(|work| work.estimated_work_units).sum();
        let policy = FrameParallelPolicy::for_current_thread_pool();
        match dirty_refresh_admission(policy, work.len(), estimated_work_units).chunk_size() {
            Some(chunk_size) => {
                work.par_iter_mut()
                    .with_min_len(chunk_size)
                    .for_each(|work| {
                        profiling::scope!("mesh::render_world::refresh_dirty_bounds::worker");
                        work.outcome =
                            refresh_dirty_bounds_work(work, scene, mesh_pool, render_context);
                    });
            }
            None => {
                for work in &mut work {
                    work.outcome =
                        refresh_dirty_bounds_work(work, scene, mesh_pool, render_context);
                }
            }
        }
        let mut outcome = RefreshOutcome::default();
        let mut refit_spaces = Vec::new();
        for work in work {
            outcome.renderer_count += work.outcome.renderer_count;
            if scene.space(work.id).is_some() {
                if work.cached.active && work.outcome.renderer_count > 0 {
                    self.update_prepared_bounds_for_set(work.id, &work.cached, &work.dirty_set);
                    refit_spaces.push(work.id);
                }
                self.spaces.insert(work.id, work.cached);
            }
        }
        if !refit_spaces.is_empty() {
            self.record_bounds_patch_refit_spaces(refit_spaces.iter().copied());
            outcome.spatial_refit_count = self
                .prepared
                .refit_cached_spatial_and_lods_for_spaces(scene, refit_spaces.iter().copied());
        }
        outcome
    }

    /// Copies refreshed per-renderer cull geometry into the existing prepared snapshot.
    fn update_prepared_bounds_for_set(
        &mut self,
        space_id: RenderSpaceId,
        cached: &RenderWorldSpace,
        dirty_set: &DirtyRendererSet,
    ) {
        for &index in &dirty_set.static_indices {
            if let Some(record) = cached.static_renderers.get(index) {
                self.apply_and_log_cull_geometry(
                    space_id,
                    false,
                    index,
                    record.instance_id,
                    record.cull_geometry,
                );
            }
        }
        for &index in &dirty_set.skinned_indices {
            if let Some(record) = cached.skinned_renderers.get(index) {
                self.apply_and_log_cull_geometry(
                    space_id,
                    true,
                    index,
                    record.instance_id,
                    record.cull_geometry,
                );
            }
        }
    }
}

/// Estimates full-space retained-refresh work from cached and current scene renderer counts.
fn estimate_full_space_refresh_work(
    cached: &RenderWorldSpace,
    scene: &(impl WorldMeshSceneRead + Sync + ?Sized),
    id: RenderSpaceId,
) -> usize {
    let cached_renderer_count = cached
        .static_renderers
        .len()
        .saturating_add(cached.skinned_renderers.len());
    let scene_renderer_count = scene
        .static_mesh_renderers(id)
        .map_or(0, |renderers| renderers.len())
        .saturating_add(
            scene
                .skinned_mesh_renderers(id)
                .map_or(0, |renderers| renderers.len()),
        );
    cached_renderer_count.max(scene_renderer_count)
}

/// Refreshes one worker-owned retained render-space for a partial renderer dirty set.
fn refresh_dirty_renderer_work(
    work: &mut DirtyRendererRefreshWork,
    scene: &(impl WorldMeshSceneRead + Sync + ?Sized),
    mesh_pool: &MeshPool,
    render_context: RenderingContext,
) -> RefreshOutcome {
    let Some(space_view) = scene.space(work.id) else {
        work.cached.active = false;
        return RefreshOutcome::default();
    };
    work.cached.active = space_view.is_active();
    if !work.cached.active {
        return RefreshOutcome::default();
    }
    work.cached.static_renderers.resize_with(
        scene
            .static_mesh_renderers(work.id)
            .map_or(0, |renderers| renderers.len()),
        Default::default,
    );
    work.cached.skinned_renderers.resize_with(
        scene
            .skinned_mesh_renderers(work.id)
            .map_or(0, |renderers| renderers.len()),
        Default::default,
    );
    refresh_renderer_set(
        &mut work.cached,
        &work.dirty_set,
        scene,
        mesh_pool,
        render_context,
        work.id,
    )
}

/// Refreshes one worker-owned retained render-space for a bounds-only dirty set.
fn refresh_dirty_bounds_work(
    work: &mut DirtyBoundsRefreshWork,
    scene: &(impl WorldMeshSceneRead + Sync + ?Sized),
    mesh_pool: &MeshPool,
    render_context: RenderingContext,
) -> RefreshOutcome {
    let Some(space_view) = scene.space(work.id) else {
        work.cached.active = false;
        return RefreshOutcome::default();
    };
    work.cached.active = space_view.is_active();
    if !work.cached.active {
        return RefreshOutcome::default();
    }
    refresh_renderer_bounds_set(
        &mut work.cached,
        &work.dirty_set,
        scene,
        mesh_pool,
        render_context,
        work.id,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn static_renderer_ref(index: usize) -> RenderWorldRendererRef {
        RenderWorldRendererRef {
            kind: RenderWorldRendererKind::Static,
            index,
        }
    }

    #[test]
    fn memoized_transform_classifier_matches_reference_ancestry_walk() {
        let parent_tables = [
            vec![-1, 0, 1, 1, 3, 4],
            vec![1, 0, 8, -1, 3, 4],
            vec![-1, 3, 1, 2],
        ];
        let root_sets = [vec![0], vec![1, 4], vec![3], vec![8], vec![-1], Vec::new()];

        for parents in &parent_tables {
            for roots in &root_sets {
                let mut classifier = TransformRootClassifier::new(parents, roots);
                for node_id in -1..=(parents.len() as i32 + 2) {
                    assert_eq!(
                        classifier.is_under_root(node_id),
                        node_is_under_any_root(parents, node_id, roots),
                        "classification differed for node {node_id}, parents {parents:?}, roots {roots:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn transform_classification_visits_each_hierarchy_node_at_most_once_per_scan() {
        const NODE_COUNT: usize = 4_096;
        let parents = (0..NODE_COUNT)
            .map(|node| if node == 0 { -1 } else { node as i32 - 1 })
            .collect::<Vec<_>>();
        let renderer_refs = (0..NODE_COUNT)
            .map(|node| vec![static_renderer_ref(node)])
            .collect::<Vec<_>>();
        let roots = (0_i32..64).collect::<Vec<_>>();
        let entries = renderer_refs
            .iter()
            .enumerate()
            .rev()
            .map(|(node_id, refs)| (node_id as i32, refs.as_slice()));

        let expansion = expand_transform_node_entries(RenderSpaceId(1), entries, &parents, &roots);

        assert_eq!(expansion.scanned_node_count, NODE_COUNT);
        assert_eq!(expansion.renderers.len(), NODE_COUNT);
        assert!(
            expansion.classified_hierarchy_node_count <= NODE_COUNT,
            "memoization must bound parent traversal by unique hierarchy nodes, independent of renderer/root count"
        );
    }

    #[test]
    fn transform_parallel_packets_are_coarse_and_bounded() {
        let space_chunk = coarsened_transform_chunk_size(25, 1, 1, 16);
        assert_eq!(space_chunk, 4);
        assert!(25usize.div_ceil(space_chunk) <= TRANSFORM_EXPANSION_MAX_TASKS);

        let recurring_scene_chunk =
            coarsened_transform_chunk_size(5_190, 64, TRANSFORM_NODE_SCAN_MIN_ENTRIES_PER_TASK, 16);
        assert_eq!(5_190usize.div_ceil(recurring_scene_chunk), 1);

        let large_scene_chunk = coarsened_transform_chunk_size(
            65_536,
            64,
            TRANSFORM_NODE_SCAN_MIN_ENTRIES_PER_TASK,
            16,
        );
        assert_eq!(large_scene_chunk, TRANSFORM_NODE_SCAN_MIN_ENTRIES_PER_TASK);
        assert!(65_536usize.div_ceil(large_scene_chunk) <= TRANSFORM_EXPANSION_MAX_TASKS);
    }

    #[test]
    fn transform_root_inputs_are_scanned_once_per_space_after_coalescing() {
        let space_id = RenderSpaceId(7);
        let coalesced = coalesce_transform_dirty_roots(vec![
            RenderWorldTransformDirty {
                space_id,
                root_node_ids: vec![1, 2],
            },
            RenderWorldTransformDirty {
                space_id,
                root_node_ids: vec![2, 3],
            },
        ]);

        assert_eq!(coalesced.len(), 1);
        assert_eq!(coalesced[0].root_node_ids, vec![1, 2, 3]);
    }
}
