//! Prepends `shaders/source/modules/globals.wgsl` to each material root, validates with naga, and
//! writes flat `shaders/target/*.wgsl` plus `OUT_DIR/embedded_shaders.rs`.
//! (For `#import` graph composition, [`naga_oil`](https://crates.io/crates/naga_oil) can be added
//! later; concatenation keeps the build graph simple while meeting the single-module WGSL target.)

use std::fs;
use std::path::PathBuf;

use naga::back::wgsl::WriterFlags;
use naga::front::wgsl::parse_str;
use naga::valid::{Capabilities, ValidationFlags, Validator};

fn strip_lines_starting_with(source: &str, prefix: &str) -> String {
    source
        .lines()
        .filter(|l| !l.trim_start().starts_with(prefix))
        .collect::<Vec<_>>()
        .join("\n")
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let globals_path = manifest_dir.join("shaders/source/modules/globals.wgsl");
    let materials_dir = manifest_dir.join("shaders/source/materials");
    let target_dir = manifest_dir.join("shaders/target");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed=shaders/source");
    println!("cargo:rerun-if-changed=build.rs");

    fs::create_dir_all(materials_dir.parent().expect("materials parent")).expect("mkdir");
    fs::create_dir_all(&target_dir).expect("mkdir target");

    let globals_raw = fs::read_to_string(&globals_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", globals_path.display()));
    let globals_body = strip_lines_starting_with(&globals_raw, "#define_import_path");

    let mut manifest_entries: Vec<serde_json::Value> = Vec::new();
    let mut embedded_arms = String::new();

    let mut material_paths: Vec<PathBuf> = fs::read_dir(&materials_dir)
        .expect("read materials")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "wgsl").unwrap_or(false))
        .collect();
    material_paths.sort();

    for path in &material_paths {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("material stem");
        let material_raw =
            fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let material_body = strip_lines_starting_with(&material_raw, "#import ");
        let combined = format!("{globals_body}\n\n{material_body}");

        let module =
            parse_str(&combined).unwrap_or_else(|e| panic!("WGSL parse {}: {e}", path.display(),));

        let has_vs = module
            .entry_points
            .iter()
            .any(|e| e.stage == naga::ShaderStage::Vertex && e.name == "vs_main");
        let has_fs = module
            .entry_points
            .iter()
            .any(|e| e.stage == naga::ShaderStage::Fragment && e.name == "fs_main");
        if !has_vs || !has_fs {
            panic!(
                "{}: expected entry points vs_main and fs_main (vertex={has_vs} fragment={has_fs})",
                path.display()
            );
        }

        let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
        let info = validator
            .validate(&module)
            .unwrap_or_else(|e| panic!("validate {}: {e}", path.display()));
        let wgsl = naga::back::wgsl::write_string(&module, &info, WriterFlags::EXPLICIT_TYPES)
            .unwrap_or_else(|e| panic!("wgsl out {}: {e}", path.display()));

        let out_path = target_dir.join(format!("{stem}.wgsl"));
        fs::write(&out_path, &wgsl).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

        manifest_entries.push(serde_json::json!({
            "stem": stem,
            "file": format!("shaders/target/{stem}.wgsl"),
            "unity_names": [],
        }));

        embedded_arms.push_str(&format!(
            "        \"{stem}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/shaders/target/{stem}.wgsl\"))),\n"
        ));
    }

    let manifest = serde_json::json!({
        "materials": manifest_entries,
        "globals_module": "shaders/source/modules/globals.wgsl",
    });
    let manifest_path = target_dir.join("manifest.json");
    fs::write(
        &manifest_path,
        serde_json::to_string_pretty(&manifest).expect("manifest json"),
    )
    .expect("write manifest");

    let embedded_rs = format!(
        r#"// Generated by `build.rs` — do not edit.

/// Flattened WGSL for `stem` (see `shaders/target/{{stem}}.wgsl`).
pub fn embedded_target_wgsl(stem: &str) -> Option<&'static str> {{
    match stem {{
{embedded_arms}        _ => None,
    }}
}}

/// Stems under `shaders/target/*.wgsl` present at build time.
pub const COMPILED_MATERIAL_STEMS: &[&str] = &[
{stems}
];

/// JSON manifest written next to composed shaders.
pub const SHADER_MANIFEST_JSON: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/shaders/target/manifest.json"));
"#,
        embedded_arms = embedded_arms,
        stems = material_paths
            .iter()
            .map(|p| {
                let s = p.file_stem().unwrap().to_str().unwrap();
                format!("    \"{s}\",")
            })
            .collect::<Vec<_>>()
            .join("\n")
    );

    let gen_path = out_dir.join("embedded_shaders.rs");
    fs::write(&gen_path, embedded_rs).expect("write embedded_shaders.rs");
}
