using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityShaderConverter.Analysis;
using UnityShaderConverter.Variants;

namespace UnityShaderConverter.Emission;

/// <summary>Emits a single <c>.slang</c> translation unit for one pass.</summary>
public static class SlangEmitter
{
    /// <summary>Builds Slang with Unity compat, optional <c>[vk::constant_id]</c> specialization bools, and baseline <c>#define</c>s.</summary>
    public static string EmitPassSlang(
        ShaderPassDocument pass,
        IReadOnlyList<string> baselineDefines,
        IReadOnlyList<SpecializationAxis> specializationAxes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("#include \"UnityCompat.slang\"");
        sb.AppendLine();
        foreach (SpecializationAxis axis in specializationAxes)
        {
            sb.Append("[vk::constant_id(").Append(axis.ConstantId).Append(")] const bool ")
                .Append(axis.SlangIdentifier).AppendLine(" = false;");
        }

        if (specializationAxes.Count > 0)
            sb.AppendLine();

        foreach (string d in baselineDefines)
        {
            if (d.Length > 0)
                sb.Append("#define ").AppendLine(d);
        }

        if (baselineDefines.Any(static s => s.Length > 0))
            sb.AppendLine();

        string programBody = StripCompilerDirectivesToString(pass.ProgramSource);
        if (specializationAxes.Count > 0)
        {
            var map = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (SpecializationAxis ax in specializationAxes)
                map[ax.Keyword] = ax.SlangIdentifier;
            programBody = HlslSpecializationPreprocessor.Rewrite(programBody, map);
        }

        foreach (string line in programBody.Split('\n'))
        {
            string lineOut = line.TrimEnd('\r');
            sb.AppendLine(lineOut);
        }

        return sb.ToString();
    }

    private static string StripCompilerDirectivesToString(string program)
    {
        var sb = new StringBuilder();
        foreach (string rawLine in program.Split('\n'))
        {
            string line = rawLine.TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("#pragma", StringComparison.Ordinal))
                continue;
            sb.AppendLine(line);
        }

        return sb.ToString().TrimEnd();
    }
}
