using System.Text;
using UnityShaderConverter.Analysis;

namespace UnityShaderConverter.Emission;

/// <summary>Emits a single <c>.slang</c> translation unit for one pass and variant.</summary>
public static class SlangEmitter
{
    /// <summary>Builds Slang source with Unity compat include and stripped pragmas.</summary>
    public static string EmitPassSlang(ShaderPassDocument pass, IReadOnlyList<string> variantDefines)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by UnityShaderConverter — do not edit.");
        sb.AppendLine("#include \"UnityCompat.slang\"");
        foreach (string d in variantDefines)
        {
            if (d.Length > 0)
                sb.Append("#define ").AppendLine(d);
        }

        sb.AppendLine();
        foreach (string line in StripCompilerDirectives(pass.ProgramSource))
            sb.AppendLine(line);

        return sb.ToString();
    }

    private static IEnumerable<string> StripCompilerDirectives(string program)
    {
        foreach (string rawLine in program.Split('\n'))
        {
            string line = rawLine.TrimEnd('\r');
            string t = line.TrimStart();
            if (t.StartsWith("#pragma", StringComparison.Ordinal))
                continue;
            yield return line;
        }
    }
}
